services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: netjes_app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "file:./dev.db"
      NEXTAUTH_SECRET: "${NEXTAUTH_SECRET:-netjes-laundry-secret}"
      NEXTAUTH_URL: "${NEXTAUTH_URL:-http://localhost:3000}"
      AUTH_SECRET: "${NEXTAUTH_SECRET:-netjes-laundry-secret}"
      FONNTE_TOKEN: "${FONNTE_TOKEN:-e5917cx2UnwvoCUptuzQ}"
    volumes:
      - sqlite_data:/app/prisma
    restart: unless-stopped

  waha:
    image: devlikeapro/waha
    container_name: netjes_waha
    ports:
      - "3005:3000"
    environment:
      - WAHA_API_KEY=netjes_waha_secret_key_2026
      - WHATSAPP_DEFAULT_SESSION=default
      - WHATSAPP_DEFAULT_ENGINE=NOWEB
      - WAHA_DASHBOARD_USERNAME=admin       # <-- Username Anda
      - WAHA_DASHBOARD_PASSWORD=rahasia123
    restart: unless-stopped

volumes:
  sqlite_data:

